# Site settings
title: Alessandro Bocci
description: 'Business Card Page'
url: 'https://github.com/alebocci/alebocci.github.io'
baseurl: ''
profilepic: '/images/foto.png'
bkimage: '/images/bk1.jpg'
#google_analytics: UA-XXXXXX-X

author:
  name: 'Alessandro Bocci'
  email: alessandro.bocci@phd.unipi.it
  gscholar: a6Cccr4AAAAJ
  orcid: 0000-0002-7000-2103
  scopus: '57222340356'
#  facebook_username: joshgerdes
  linkedin_username:  alessandro-bocci-312b89281
  description: 'PostDoctoral Reaseracher in Computer Science'
  place: 'Department of Computer Science, University of Pisa'
  placeWebsite: 'https://www.di.unipi.it/en/'
  

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
